### ISSUE TITLE
⚡️ Migrate from TSLint to ESLint

### ISSUE THREAD

**Issue by p-fruck** [tjarbo/discord-moodle-bot#105]
### Description
Since TSLint has been [deprecated](https://github.com/palantir/tslint/issues/4534) quite a while ago, I'd like to recommend the switch to ESLint in the backend package. It would be nice to have some assistance performing this switch in order to specify the correct ruleset :wink:

**Comment by NathanAdhitya** [comment]
There is this CLI app: https://www.npmjs.com/package/tslint-to-eslint-config. Tried it briefly on my local dev setup (lerna is a pain to work with so far), and it seems to parse this project's tslint rules correctly. Haven't bothered to make a PR yet, but I believe the move is a good step towards better code quality. It'd also be nice if the code style could be the same as the frontend (airbnb style) to have better consistency across the two packages.

**Comment by tjarbo** [comment]
Cool, thank you! AirBnB stlye on both packages sounds like a good idea - need to see how the code will look like. Perhaps can cause many merge conflicts, so we should do this if there are not that much other/wip branches. From our side, we are currently focused on implementing new features like new connectors and refactoring the moodle implementation for a better UX.
