### ISSUE TITLE
📝 API-Dokumentationen nachholen

### ISSUE THREAD

**Issue by tjarbo** [tjarbo/discord-moodle-bot#12]
Es fehlen noch die Dokumentationen für folgende Endpunkte:
- set-course-list
- set-discord-channel
- set-refresh-rate

## Unteraufgaben
- [x] GET - settings/refreshRate
- [x] PUT - settings/refreshRate
- [x] GET - settings/courses
- [x] PUT - settings/courses/:id
- [x] GET - settings/discordChannel
- [x] PUT - settings/discordChannel

**Comment by antonplagemann** [comment]
Änderungen wurden mit Pull-Request [https://github.com/tjarbo/discord-moodle-bot/pull/27](url) implementiert.
