### ISSUE TITLE
🐛 Missing error message on registration page

### ISSUE THREAD

**Issue by p-fruck** [tjarbo/discord-moodle-bot#156]
### Description
When registering a new account with a name that doesn't match the regex, users do not get any hint what's wrong.

### Steps to reproduce:
Try to register a new account with a valid token, but invalid username, eg. a username that contains a space. You cannot click the register button now.

### What was supposed to happen?
A little hint should appear, how the username should be formatted.

**Screenshots**
Please show a little hint, why this username isn't working
![image](https://user-images.githubusercontent.com/30511472/127619207-3de16bcf-4d0b-4044-82a0-cbcad6d8dfd6.png)

This is how it's looking when you choose a correct username
![image](https://user-images.githubusercontent.com/30511472/127619442-206eb12c-f092-4120-8824-0a6c01c4639b.png)

**Comment by tjarbo** [comment]
Closed with #167
