### ISSUE TITLE
Deploy to Heroku button broken

### ISSUE THREAD

**Issue by SuperSayf** [tjarbo/discord-moodle-bot#172]
### Description
Yo, awesome work on this project, just wanted to let you know the Heroku Deploy on the readme is not using the correct link for the app.json

### Steps to reproduce:
1. Go to 'https://github.com/tjarbo/discord-moodle-bot/wiki/Setup-with-heroku-and-mongodb-atlas'
2. Click on 'Deploy to Heroku'
3. See error

### What was supposed to happen?
Suppose to load the proper app.json and allow the user to enter the environment variables

### Further information:
Just link it to your app.json, it works when I did that

**Environment(please complete the following information):**
 - OS: Windows 11
 - Brave
 - Version 1.30.89 Chromium: 94.0.4606.81 (Official Build) (64-bit)

**Screenshots**
What I see when I click the current deployment button:
[https://i.imgur.com/EzaQ4ns.png](url)

**Comment by tjarbo** [comment]
Hey @SuperSayf
thanks for open an issue! You are right, looks like a copy and paste mistake :sweat_smile: I have now fixed the button in our new documentation for version 1.0 at https://docs.tjarbo.me/moodle-notification-service/1.0.0/setup-with-heroku-mongodb-atlas/. Or you can click here on: 
[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/tjarbo/discord-moodle-bot)

But to be honest, we have never really tested the performance of the fmdb running on Heroku. It would be awesome if you can provide us with some feedback about the performance or any issue that arise. Do not forget to select an "Always-On" dyno, as the fmdb scrapes data regular from moodle.

Best regards!

**Comment by SuperSayf** [comment]
@tjarbo 
Thanks for fixing the issue 😄 

Regarding the performance on Heroku, it runs perfectly, I have been running it for about 3 days now, and there are no problems. This is truly an amazing project, the front-end looks amazing also, and the website you made to generate the moodle token was really helpful also.

Keep up the amazing work 😆 

Best regards!

**Comment by tjarbo** [comment]
@SuperSayf 
Thank u very much! This is great :tada: Hopefully we will be able to release version 2.0 in the near future.
