### ISSUE TITLE
🐛 fmdb.tjarbo.me does not support passwords/usernames with special characters.

### ISSUE THREAD

**Issue by NathanAdhitya** [tjarbo/discord-moodle-bot#188]
### Description
Passwords with special characters, e.g. &, are not escaped properly in fmdb.tjarbo.me

**Comment by NathanAdhitya** [comment]
fmdb.tjarbo.me hasn't been updated yet it seems. The PR has been merged though. Looking forward for the subdomain to be updated.

**Comment by tjarbo** [comment]
Oh yes, you are right. Github Page were still on main branch. I have updated the settings. Pipline https://github.com/tjarbo/discord-moodle-bot/actions/runs/1657923308 is now running

**Comment by tjarbo** [comment]
Uh, but bad review from my side - I see, that I forgot the that the username/password is used three times within the code. I will make a PR

**Comment by NathanAdhitya** [comment]
Works properly now. Hooray.
