### ISSUE TITLE
⚡️ URL des Backends in die Environment Variablen auslagern

### ISSUE THREAD

**Issue by antonplagemann** [tjarbo/discord-moodle-bot#34]
Im Moment ist die Backend URL noch hardcoded in `packages/frontend/src/store/index.js` zu finden. Diese sollte in die Environment Variablen ausgelagert werden um auf den jeweiligen Server anpassbar zu sein.
Betroffene Zeile: `const URL = 'http://localhost:4040/api'`

**Comment by tjarbo** [comment]
Wichtiger Punkt 👍! Diese Anpassung ist Teil von #17

**Comment by tjarbo** [comment]
Done :heavy_check_mark:
