### ISSUE TITLE
🐛 Neuladen des Dashboards leitet auf die Anmeldeseite

### ISSUE THREAD

**Issue by antonplagemann** [tjarbo/discord-moodle-bot#42]
### Beschreibe den Bug
Wenn man sich auf dem Dashboard befindet und die Seite neu lädt landet man auf der Anmeldeseite obwohl man schon angemeldet ist. Lädt man dann die Anmeldeseite neu landet man wieder auf dem Dashboard.

### Schritte zum Reproduzieren:
1. Go to 'dashboard'
2. Click on 'reload page'
3. See error (login screen)
4. Click 'reload page'
5. See dashboard again

### Was sollte eigentlich passieren?
Nach dem Neuladen der Dashboard Seite sollte die diese wieder angezeigt werden.

### Weiteres:
-

**Umgebung:**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 78.0.2

**Comment by tjarbo** [comment]
👍 Werde mal morgen schauen, ob ich was finde
