### ISSUE TITLE
✨ Manueller Fetch-Button

### ISSUE THREAD

**Issue by antonplagemann** [tjarbo/discord-moodle-bot#58]
> **Als ein** User
> **will ich** einen Button haben welcher direkt einen Moodle-Fetch (und Notification) auslöst
> **sodass** ich nicht geduldig auf das nächste Intervall warten muss.

## Beschreibung:
Ein Button mit dem man den Fetch manuell anstoßen kann wäre manchmal praktisch. Der Mensch ist schließlich ungeduldig. In gleichem Schritt sollte die Moodle-Verwaltung nochmal optimiert werden.

### 🟢 In Scope:

@tjarbo 
* Zusammenfügen der MongoDB Moodle Settings
* Dokumentation aktualisieren
* Endpunkt `/api/fetch` hinzufügen

@antonplagemann:
* Button im Statusfeld hinzufügen
* Nachricht bei erfolgreicher Ausführung anzeigen
* Hinzufügen des neuen Endpunktes im Frontend

### 🔴 Not in Scope:
* Statusboard-Werte verändern.
* Fetch-Intervall anpassen.
* Neue Endpunkt für Moddle-Daten verwenden. 
* Neue Moodle-Endpunkte definieren und umschreiben

## Wie soll das Ergebnis aussehen?
`Fetch and Notify` Button auf der Statusseite neben dem `Aktualisieren` Button (beide halbe Größe).

**Comment by tjarbo** [comment]
Wäre es auch möglich, dass etwas UI freundlciher zu machen ? Anstatt einen weiteren *großen* Button unten drunter, wäre mein Vorschlag, dass beide Buttons:
- Normal groß
- Nebeneinander in eine Zeile
- Rechts-alignt in der "Zelle"

**Comment by antonplagemann** [comment]
> 
> 
> Wäre es auch möglich, dass etwas UI freundlicher zu machen? Anstatt einen weiteren _großen_ Button unten drunter, wäre mein Vorschlag, dass beide Buttons:

>     Nebeneinander in eine Zeile
Find ich gut, angenommen 👍

**Comment by antonplagemann** [comment]
![grafik](https://user-images.githubusercontent.com/54081139/95627589-babb6d80-0a7c-11eb-8d66-0e04b7e36d27.png)
Passt so?

**Comment by tjarbo** [comment]
Perfekt 👌

**Comment by tjarbo** [comment]
> ![grafik](https://user-images.githubusercontent.com/54081139/95627589-babb6d80-0a7c-11eb-8d66-0e04b7e36d27.png)
> 
> ![grafik](https://user-images.githubusercontent.com/54081139/95627720-f2c2b080-0a7c-11eb-838c-c2a54a4dc59f.png)
> 
> 
> 
> Passt so?

Perfekt 👌

**Comment by antonplagemann** [comment]
Kannst du bei der API zurückmelden ob der Fetch erfolgreich war?
Als JSON oder besser als HTTP-Statuscode?
Würde dann die Frontend Notifications entsprechend programmieren.
Des Weiteren würde ich gerne dabei das Statusboard noch leicht anpassen:
- NextFetch als Wert in der Datenbank welcher durch die Funktion `continuousFetchAndNotify()` geschrieben wird.
- Änderung der Status-API sodass NextFetch mit zurückgegeben wird.
- Anpassung vom Statusboard im Frontend an die erweiterte Status-API.

Das behebt dann folgende Bugs:
- NextFetch wird direkt nach dem Start des Bots nicht korrekt berechnet.
- Nextetch wird direkt nach der Änderung des Intervalls nicht korrekt berechnet.
- NextFetch wird direkt nach einem manuellen Fetch nicht korrekt berechnet.

**Comment by tjarbo** [comment]
Ich kann versuchen, dass der Endpunkt eine  `ApiResponse` zurück gibt. Ganz sicher bin ich mir noch nicht, wie das funktionieren wird. Dann kannst du für die Verarbeitung der Antwort `ApiReponse.status` einfach nutzen :+1: 

Für das Anpassen des Status-Boards würde ich ein separates Ticket aufmachen, da es den Scope dieses Tickets sprengen würde (kleine handliche Aufgaben-Packete :gift: :baby: )

**Comment by tjarbo** [comment]
Soweit sind alle Änderungen implementiert :+1:
Es müssen nur anschließend noch neue Tickets für die folgenden Verbesserungen angelegt werden:

- StoreUtil um einen **blocked** Zustand erweitern, damit Requests ohne Rückgabe nicht unnötig einen eigenen Store benötigen
- Die vorgeschlagenen Änderungen bezüglich *NextFetch*
- Nachholen der Unit-Tests für die Status-Komponente 

@antonplagemann Könntest du eine PR für dieses Ticket erstellen ?
