### ISSUE TITLE
🐛 Aufgabe ohne Abgabedatum wird nicht korrekt verarbeitet

### ISSUE THREAD

**Issue by antonplagemann** [tjarbo/discord-moodle-bot#60]
### Beschreibe den Bug
Wenn auf Moodle eine Aufgabe ohne Abgabedatum (also ohne Abgabemöglichkeit) veröffentlicht wird, postet der Bot dennoch eine Nachricht mit dem Titel "Neue Abgabe", dem Text "<Dokument> ist abzugeben." und einem Abgabedatum von 1970 (Unix-Timestamp 0). Ein solcher Fall sollte besser anders bzw. eindeutiger gepostet werden.

### Schritte zum Reproduzieren:
Kann nicht reproduziert werden.

### Was sollte eigentlich passieren?
Eine Meldung das eine Aufgabe ohne Abgabemöglichkeit veröffentlicht wurde sollte gepostet werden.

### Weiteres:

**Umgebung(please complete the following information):**
 - Irrelevant

**Weitere Informationen**
Nope

**Comment by tjarbo** [comment]
Hättest du einen Vorschlag, wie die Ausgabe aussehen soll ?
> **KURS1 - Neue Abgabe hinzugefügt!**
>   :information_source: "Übungsblatt 01" ist abzugeben
>   :alarm_clock: bis _`keine Zeit gesetzt`_

**Comment by tjarbo** [comment]
> Hättest du einen Vorschlag, wie die Ausgabe aussehen soll ?
> 
> > **KURS1 - Neue Abgabe hinzugefügt!**
> > information_source "Übungsblatt 01" ist abzugeben
> > alarm_clock bis _`keine Zeit gesetzt`_

@antonplagemann wie findest du das ?

**Comment by antonplagemann** [comment]
Find ich super! 🤓
