### ISSUE TITLE
🔎 Probleme mit Token generierung

### ISSUE THREAD

**Issue by FreshImmuc** [tjarbo/discord-moodle-bot#66]
Hello. 
This site: https://fmdb.tjarbo.me/
Does not work for me it says "Ungültige anmeldedaten. Versuche es noch einmal" (wich means Incorrect Login Data in german)

But my password is 100% correct and my username also. The URL is also right...

So idk what to do pls help #63

**Comment by FreshImmuc** [comment]
could i just use the webservices key?

**Comment by FreshImmuc** [comment]
or can i contact the Owners of the moodle and ask them about the Key? If so, what should I ask them about? The API token?

**Comment by FreshImmuc** [comment]
Ich hab grad gesehen dass du deutsch bist also ich hab grad unseren Besitzer nach der richtigen URL gefragt und er hat sie mir gegeben. Feier deine Arbeit echt Weiter so!

**Comment by tjarbo** [comment]
Moin, vielen Dank :100: Der Bot ist zwar noch nicht zu 100% fertig und hat noch ein paar Macken, aber vielleicht kann er euch ja trotzdem im Moodle-Alltag unterstützen!  Solltest du Bugs finden, melde sie auf jeden Fall :wink:

Vielleicht ist dein Problem mit https://fmdb.tjarbo.me ja ein Allgemeines - haben es selbstverständlich nicht für alle verfügbaren Moodle-Platformen getest. Kannst du uns das näher erläutern ? @FreshImmuc

**Comment by tjarbo** [comment]
Das hat sich erledigt :white_check_mark:
