### ISSUE TITLE
📥 Readme aktualisieren

### ISSUE THREAD

**Issue by tjarbo** [tjarbo/discord-moodle-bot#75]
## Was ist zu tun ?
Ich würde gerne mal das Repo etwas aufräumen und die Readme dabei etwas fancy-ger gestalten :art: 

Übersicht:

- [x] Readme updaten
- [x] Issue Templates aktualisieren
- [x] Pull Request Template aktualisieren

## Informationen
Wer: *siehe Assignee*
Bis wann: bis zu den Feiertagen :christmas_tree: :laughing:

**Comment by antonplagemann** [comment]
M. E. etwas unklares Issue, was bedeutet "aufgepimpt"? :-)

**Comment by tjarbo** [comment]
Schau einfach mal in die Branch ;)

**Comment by tjarbo** [comment]
Ich passe die Issue-Beschreibung später mal an, wenn ich alle Änderungen gesammelt habe.
