### ISSUE TITLE
Lernraum Berlin

### ISSUE THREAD

**Issue by Stektax** [tjarbo/discord-moodle-bot#83]
Hallo. Der Lernraum Berlin wird nicht als Moddle oderso erkannt. [Lernraum Berlin](https://portal.lernraum-berlin.de/moodle/login/index.php) Der Lernaum Berlin ist eine Website die die Schüler in den Corona Zeiten mit aufgaben versorgt. Nun wird aber die Verbindung zum Lernraum nicht hergestellt. 
![unknown1](https://user-images.githubusercontent.com/77275742/104178581-e26afa80-540a-11eb-8e96-6bc2c88ddb73.png)

Ich habe den Lernraum angeschrieben und sie meinten dass der Discord bot also die Tokengenerierung nicht mit einer SSO-Authentifizierung kompatibel ist.
Sie meinten auch dass man vielleicht den Token der schon erzeugt wurde vom Lernraum benutzen könnte. Vorschlag für neues Feature ist dass du halt vielleicht noch eine Unterstützung für den Lernraum Berlin hinzufügst. Er wird von ganz Berlin benutzt und ist sehr unübersichtlich also es wäre wirklich sehr sehr Hilfreich wenn du dieses Feature noch hinzufügst.

LG

**Comment by tjarbo** [comment]
Moin @Stektax 
vielen Dank, dass du ein Issue aufgemacht hast (kann sein, dass ich das eventuell später in eine [Discussion](https://github.com/tjarbo/discord-moodle-bot/discussions) verschiebe)!  Du bist tatsächlich nicht der erste, welcher vom Lernraum Berlin kommt. Leider haben wir nicht die Ressourcen momentan SSO-Support für fmdb.tjarbo.me zu implementieren. Aber da die Moodle-App auch unterstützt wird, sollte es trotzdem klappen :clinking_glasses: 

Nun ist etwas manuelle Arbeit notwendig (normal nimmt dir das fmdb.tjarbo.me ab). Gehen wir dafür die entsprechenden Variablen einzeln durch: 

* Für `MOODLE_BASE_URL` setzt du den Wert `https://www.lernraum-berlin.de/vXundX` (setzte natürlich die passenden Zahlen ein!) oder `https://www.lernraum-berlin.de/osz` ein. (Es kann nur *ein* Verbund überwacht werden, da es sich allen Anschein nach um separate Instanzen handelt)
* Für `MOODLE_USERID` klickt du oben rechts auf dein Profilbild und öffnest dein _Profil_. Anschließend findest du den Query-Paramater `?userid=X` in der Adresszeile deines Browsers. Setzt diese Nummer entsprechend als Wert ein. 
* Für `MOODLE_TOKEN` kopierst du den Schlüssel, welcher unter "Einstellungen" > "Sicherheitsschlüssel" bei "Moodle mobile web service" angezeigt wird. 

> :warning: Beachte, dass für alle Schritte du einen Verbund geöffnet haben musst. `https://portal.lernraum-berlin.de/moodle/` ist die falsche Instanze

**Comment by Stektax** [comment]
Hallo. Ich finde meine .env Datei nichtmehr 😅

Gibt es irgendeine möglichkeit den Pfad herauszufinden?
LG

**Comment by Stektax** [comment]
Okay also hab die Steps jtz alle durch und moodle verbindung ist auf "Ok" 👌
![image](https://user-images.githubusercontent.com/77275742/104313984-144a9280-54d9-11eb-9002-2ae145520124.png)
Also wenn jtz neue Dateien im Lernraum hochgeladen werden, dann schickt der Bot diese oder den Link dazu in den DC channel?

LG

**Comment by Stektax** [comment]
Und eine Idee für ein neues Feature wäre dann noch eine Rich Presence für den Bot.
Bitte bleib dran und verbesser den Bot noch mehr denn er ist echt super und sehr hilfreich vorallem in der Corona Zeit! 👍🏻

LG

**Comment by tjarbo** [comment]
> Okay also hab die Steps jtz alle durch und moodle verbindung ist auf "Ok" ok_hand
> ![image](https://user-images.githubusercontent.com/77275742/104313984-144a9280-54d9-11eb-9002-2ae145520124.png)
> Also wenn jtz neue Dateien im Lernraum hochgeladen werden, dann schickt der Bot diese oder den Link dazu in den DC channel?
> 
> LG

Wenn eine neue Datei hochgeladen wurde, schickt der Link eine Benachrichtigung + Link zur Datei. Wenn du bei Moodle noch eine aktive Session hast, wird der Download direkt gestartet.

**Comment by tjarbo** [comment]
> Und eine Idee für ein neues Feature wäre dann noch eine Rich Presence für den Bot.
> Bitte bleib dran und verbesser den Bot noch mehr denn er ist echt super und sehr hilfreich vorallem in der Corona Zeit! 👍🏻
> 
> LG

@Stektax vielen Dank! Ist natürlich immer eine Sache der verfügbaren Zeit :sweat_smile: 

Jetzt muss ich aber mal zurückfragen: Was ist eine _Rich Presence_ und welche neue Funktion/neuen Funktionen erhält dadurch der Bot ?

**Comment by Stektax** [comment]
Hallo,
eine Rich Presence ist so etwas hier:
![image](https://user-images.githubusercontent.com/77275742/104431772-947c0100-5588-11eb-9380-948925823763.png)
Bei Bots sieht das dann eher so aus:
![image](https://user-images.githubusercontent.com/77275742/104432142-ffc5d300-5588-11eb-8d7a-a348eb473c0d.png)


ich weiss das ist eher eine Kosmetische Sache aber wär halt trotzdem ein cooles neues Feature.

Was mir auchnoch aufgefallen ist, ist dass der Bot die Videomeetings (sind neu dazu gekommen) als Abzugebene Datei anzeigt und nicht als Meeting.
![image](https://user-images.githubusercontent.com/77275742/104432645-824e9280-5589-11eb-976c-2cbfdac1d75c.png)


LG

**Comment by tjarbo** [comment]
Moin,
vielen Dank! Diese Funktion hatten wir gar nicht auf dem Schirm gehabt, aber ließe sich sicherlich gut nutzen um beispielsweise anzugeben, wann der Bot das nächste mal aktualisiert :smile: Es wäre cool, wenn du dem Projekt "nen Stern geben kannst" damit es mehr Reichweite bekommt und vergiss nicht unter "watch > custom > releases" auszuwählen, damit du nicht verpasst, wenn eine neue Funktion veröffentlicht wird :smile: 

Wegen dem Bug, mache bitte ein neues Issue auf, damit andere mit einem ähnlichem Problem es Thema leichter finden :+1: 
Viele Grüße :wave:
